#!/usr/bin/env bash
# Spendcap — bump build, archive, export, upload to TestFlight.
#
# Build number lives in project.yml (CURRENT_PROJECT_VERSION) since
# the pbxproj is generated by xcodegen. SHIP_RUN_UI=1 also runs UI
# tests as a ship gate (default is unit-only).

set -euo pipefail

cleanup() {
    pkill -f 'log stream .*altool' 2>/dev/null || true
}
trap cleanup EXIT INT TERM

cd "$(dirname "$0")/.."

if [[ ! -f scripts/asc-config.env ]]; then
    echo "error: scripts/asc-config.env missing. Copy from .example and fill in." >&2
    exit 1
fi

# shellcheck disable=SC1091
source scripts/asc-config.env

PROJECT="Spendcap.xcodeproj"
SCHEME="Spendcap"
PROJECT_YML="project.yml"
ARCHIVE="build.nosync/Spendcap.xcarchive"
EXPORT_DIR="build.nosync/export"
IPA="$EXPORT_DIR/Spendcap.ipa"

echo "==> running tests"
if [[ "${SHIP_RUN_UI:-0}" == "1" ]]; then
    ./scripts/run_tests.sh all
else
    ./scripts/run_tests.sh unit
fi

current=$(grep -m1 'CURRENT_PROJECT_VERSION:' "$PROJECT_YML" | sed -E 's/.*"([0-9]+)".*/\1/')
next=$((current + 1))
echo "==> bumping build $current -> $next"
sed -i '' "s/CURRENT_PROJECT_VERSION: \"$current\"/CURRENT_PROJECT_VERSION: \"$next\"/" "$PROJECT_YML"

echo "==> regenerating xcodeproj"
./scripts/generate.sh >/dev/null

ASC_AUTH_FLAGS=(
    -authenticationKeyPath "$ASC_KEY_PATH"
    -authenticationKeyID "$ASC_KEY_ID"
    -authenticationKeyIssuerID "$ASC_ISSUER_ID"
)

echo "==> archiving"
rm -rf build.nosync
mkdir -p build.nosync
xcodebuild \
    -project "$PROJECT" \
    -scheme "$SCHEME" \
    -configuration Release \
    -destination "generic/platform=iOS" \
    -archivePath "$ARCHIVE" \
    -allowProvisioningUpdates \
    "${ASC_AUTH_FLAGS[@]}" \
    archive

echo "==> exporting IPA"
xcodebuild \
    -exportArchive \
    -archivePath "$ARCHIVE" \
    -exportPath "$EXPORT_DIR" \
    -exportOptionsPlist ExportOptions.plist \
    -allowProvisioningUpdates \
    "${ASC_AUTH_FLAGS[@]}"

echo "==> uploading to TestFlight"
xcrun altool \
    --upload-app \
    -f "$IPA" \
    -t ios \
    --apiKey "$ASC_KEY_ID" \
    --apiIssuer "$ASC_ISSUER_ID"

echo "==> shipped build $next"

# Keep internal-tester auto-distribution on — idempotent, so accidental
# ASC UI changes don't break the next ship's distribution.
echo "==> verifying internal tester auto-distribution"
python3 scripts/configure_internal_testers.py || \
    echo "warning: configure_internal_testers.py reported a problem; check ASC manually"
