#!/usr/bin/env bash
# Spendcap — quality gates, bump build, archive, export, upload to TestFlight.
#
# Build number lives in project.yml (CURRENT_PROJECT_VERSION) since
# the pbxproj is generated by xcodegen.
#
# Apple's four quality checks run before every TestFlight upload and follow
# the app as screens come and go (owner, 2026-10-02, all apps):
#   1. Swift Testing  — the @Test suites in SpendcapTests must run
#   2. XCUITest       — the whole UI suite (no longer opt-in) incl.
#                       AccessibilityAuditTests: sign-in, every tab found at
#                       run time, light + dark, the largest text size
#   3. XCTMetric      — PerformanceTests, judged by scripts/perf_gate.py
#                       against the median of the last 5 passing ships
#   4. MetricKit      — Services/MetricsReporter.swift still subscribed; the
#                       Xcode Organizer's field numbers printed (report only)
# plus scripts/coverage_gate.py: every screen is executed by a test, and no UI
# test queries an identifier the app no longer has.
#
#   SIMULATOR_ID=<free simulator> ./scripts/ship.sh

set -euo pipefail

cleanup() {
    pkill -f 'log stream .*altool' 2>/dev/null || true
}
trap cleanup EXIT INT TERM

cd "$(dirname "$0")/.."

if [[ ! -f scripts/asc-config.env ]]; then
    echo "error: scripts/asc-config.env missing. Copy from .example and fill in." >&2
    exit 1
fi

# shellcheck disable=SC1091
source scripts/asc-config.env

PROJECT="Spendcap.xcodeproj"
SCHEME="Spendcap"
PROJECT_YML="project.yml"
ARCHIVE="build.nosync/Spendcap.xcarchive"
EXPORT_DIR="build.nosync/export"
IPA="$EXPORT_DIR/Spendcap.ipa"

PY="${PY:-$HOME/.venvs/spendcap/bin/python}"
GATES="build.nosync/gates"
mkdir -p "$GATES"

# Regenerate BEFORE testing: a Swift file added since the last generate is in
# no target, and its tests silently never run (Marracat, 2026-10-03).
echo "==> regenerating xcodeproj"
./scripts/generate.sh >/dev/null

echo "==> MetricKit still wired (metrics + diagnostics)"
grep -q "MXMetricManager.shared.add" Spendcap/Services/MetricsReporter.swift \
  && grep -q "\[MXDiagnosticPayload\]" Spendcap/Services/MetricsReporter.swift \
  && grep -rq "MetricsReporter.shared.start()" Spendcap/App \
  || { echo "error: MetricsReporter (MetricKit) is no longer subscribed at launch" >&2; exit 1; }

echo "==> unit + UI tests"
./scripts/run_tests.sh ship "$GATES/Ship.xcresult"

# xcodebuild passes with zero tests run, so each gate proves it ran. Swift
# Testing cases are the ones not named test…() (XCTest's convention).
xcrun xcresulttool get test-results tests --path "$GATES/Ship.xcresult" | python3 -c '
import json, sys
n = 0
def walk(node):
    global n
    for c in node.get("children", []):
        if c.get("nodeType") == "Test Case" and not c["name"].startswith("test") and c.get("result") == "Passed":
            n += 1
        walk(c)
for t in json.load(sys.stdin)["testNodes"]:
    walk(t)
print(f"==> Swift Testing: {n} test(s) passed")
sys.exit(0 if n else 1)' || { echo "error: no Swift Testing tests ran" >&2; exit 1; }
xcrun xcresulttool get test-results tests --path "$GATES/Ship.xcresult" | grep -q "AccessibilityAuditTests" \
    || { echo "error: the accessibility audit did not run" >&2; exit 1; }

echo "==> every screen is exercised by a test"
python3 scripts/coverage_gate.py "$GATES/Ship.xcresult"

echo "==> performance"
./scripts/run_tests.sh perf "$GATES/Perf.xcresult"
python3 scripts/perf_gate.py "$GATES/Perf.xcresult" --record

echo "==> Xcode Organizer: what real phones reported for recent builds"
"$PY" scripts/organizer_report.py || echo "warning: Organizer report unavailable"

# A green suite does not prove the app starts — XCUITest launches through its
# own harness. Prove a cold launch works before shipping. SHIP_SKIP_SMOKE=1
# escapes it if no simulator is available.
if [[ "${SHIP_SKIP_SMOKE:-0}" == "1" ]]; then
    echo "==> skipping smoke test (SHIP_SKIP_SMOKE=1)"
else
    echo "==> smoke-testing a simulator launch"
    ./scripts/smoke_test.sh
fi

current=$(grep -m1 'CURRENT_PROJECT_VERSION:' "$PROJECT_YML" | sed -E 's/.*"([0-9]+)".*/\1/')
next=$((current + 1))
echo "==> bumping build $current -> $next"
sed -i '' "s/CURRENT_PROJECT_VERSION: \"$current\"/CURRENT_PROJECT_VERSION: \"$next\"/" "$PROJECT_YML"

echo "==> regenerating xcodeproj"
./scripts/generate.sh >/dev/null

ASC_AUTH_FLAGS=(
    -authenticationKeyPath "$ASC_KEY_PATH"
    -authenticationKeyID "$ASC_KEY_ID"
    -authenticationKeyIssuerID "$ASC_ISSUER_ID"
)

echo "==> archiving"
rm -rf build.nosync
mkdir -p build.nosync
xcodebuild \
    -project "$PROJECT" \
    -scheme "$SCHEME" \
    -configuration Release \
    -destination "generic/platform=iOS" \
    -archivePath "$ARCHIVE" \
    -allowProvisioningUpdates \
    "${ASC_AUTH_FLAGS[@]}" \
    archive

echo "==> exporting IPA"
xcodebuild \
    -exportArchive \
    -archivePath "$ARCHIVE" \
    -exportPath "$EXPORT_DIR" \
    -exportOptionsPlist ExportOptions.plist \
    -allowProvisioningUpdates \
    "${ASC_AUTH_FLAGS[@]}"

echo "==> uploading to TestFlight"
xcrun altool \
    --upload-app \
    -f "$IPA" \
    -t ios \
    --apiKey "$ASC_KEY_ID" \
    --apiIssuer "$ASC_ISSUER_ID"

echo "==> shipped build $next"

# Keep internal-tester auto-distribution on — idempotent, so accidental
# ASC UI changes don't break the next ship's distribution.
echo "==> verifying internal tester auto-distribution"
python3 scripts/configure_internal_testers.py || \
    echo "warning: configure_internal_testers.py reported a problem; check ASC manually"
